/* eslint-disable @next/next/no-page-custom-font */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Header() {
  return (
    <>
      <title>Felipe Scherer Portifolio</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet"
      />
    </>
  )
}
