import { ThemeProvider } from '@/context/theme.context'
import Script from 'next/script'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script>
        {`
        if (window.matchMedia &&
        window.matchMedia('(prefers-color-scheme:dark)').matches)
        {
          document.documentElement.setAttribute("data-theme", "dark")
        }
        else {
          document.documentElement.setAttribute("data-theme", "light")
        }
  `}
      </Script>
    </html>
  )
}
